#'Extracts fitted values from \code{\link{harmonic.regression}} object
#'
#'Create fitted values (y) for a sepcific time series (x). The fit obejct should be generated by \code{\link{harmonic.regression}}
#'
#'@param hr.out.object Output object from \code{\link{harmonic.regression}}
#'@param inputTime Numeric vestor for time series to be fitted by harmonic regression.
#'@param tau Period of harmonic regression, defaults to 24. \code{tau} should be the same value used in \code{link{harmonic.regresion}}.
#'@param trend.degree Degree of polynomial trend function used in \code{\link{harmonic.regression}}. \code{trend.deggree} should be the same value used in \code{link{harmonic.regresion}}.
#'@return fitted values for provided time series
#'@examples
#'#A detailed example will come here
#'@export

#TODO: create proper examples for this function

fittedHR <- function(hr.out.object = hrOut, inputTime, tau = 24, trend.degree = 0){
  Tau <- tau
  trend.degree <- trend.degree
  inputtime <- inputTime
  if(colnames(hr.out.object$coeffs)[1] == "(Intercept)"){
    colnames(hr.out.object$coeffs)[1] <- "intercept"
    intercept <- 1
  }

  out <- lapply(1:dim(hr.out.object$coeffs)[1], function(x){
    hr.formula <- paste(hr.out.object$coeffs[x,], colnames(hr.out.object$coeffs), sep = " * ", collapse = " + ")
    eval(parse(text = hr.formula))
  })
  out <- do.call(cbind, out)
  colnames(out) <- rownames(hr.out.object$pars)
  return(out)
}
